name: Python CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install system dependencies for building Python packages
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libffi-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-binary :all: -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest tests

    - name: Run mypy for type checking
      run: |
        mypy .

    - name: Run black for code formatting check
      run: |
        black --diff --check .

    - name: Run isort for import sorting check
      run: |
        isort --check-only .

    - name: Run flake8 for linting
      run: |
        flake8 .
